// Reliable fallback data for country / timezone selectors.
// We prefer the browser's Intl data, but fall back to these static lists so the
// dropdowns are never empty (some runtimes / older browsers lack
// Intl.supportedValuesOf).

// Complete ISO 3166-1 country list. This is the single source of truth for the
// country dropdown so ALL real countries are always shown, regardless of the
// browser's Intl support. Intl.DisplayNames is used only for nicer localized
// display names when available.
export const ISO_COUNTRIES: { code: string; name: string }[] = [
  { code: "AD", name: "Andorra" }, { code: "AE", name: "United Arab Emirates" },
  { code: "AF", name: "Afghanistan" }, { code: "AG", name: "Antigua and Barbuda" },
  { code: "AI", name: "Anguilla" }, { code: "AL", name: "Albania" },
  { code: "AM", name: "Armenia" }, { code: "AO", name: "Angola" },
  { code: "AQ", name: "Antarctica" }, { code: "AR", name: "Argentina" },
  { code: "AS", name: "American Samoa" }, { code: "AT", name: "Austria" },
  { code: "AU", name: "Australia" }, { code: "AW", name: "Aruba" },
  { code: "AX", name: "Åland Islands" }, { code: "AZ", name: "Azerbaijan" },
  { code: "BA", name: "Bosnia and Herzegovina" }, { code: "BB", name: "Barbados" },
  { code: "BD", name: "Bangladesh" }, { code: "BE", name: "Belgium" },
  { code: "BF", name: "Burkina Faso" }, { code: "BG", name: "Bulgaria" },
  { code: "BH", name: "Bahrain" }, { code: "BI", name: "Burundi" },
  { code: "BJ", name: "Benin" }, { code: "BL", name: "Saint Barthélemy" },
  { code: "BM", name: "Bermuda" }, { code: "BN", name: "Brunei Darussalam" },
  { code: "BO", name: "Bolivia" }, { code: "BQ", name: "Bonaire, Sint Eustatius and Saba" },
  { code: "BR", name: "Brazil" }, { code: "BS", name: "Bahamas" },
  { code: "BT", name: "Bhutan" }, { code: "BV", name: "Bouvet Island" },
  { code: "BW", name: "Botswana" }, { code: "BY", name: "Belarus" },
  { code: "BZ", name: "Belize" }, { code: "CA", name: "Canada" },
  { code: "CC", name: "Cocos (Keeling) Islands" }, { code: "CD", name: "Congo (Democratic Republic)" },
  { code: "CF", name: "Central African Republic" }, { code: "CG", name: "Congo" },
  { code: "CH", name: "Switzerland" }, { code: "CI", name: "Côte d'Ivoire" },
  { code: "CK", name: "Cook Islands" }, { code: "CL", name: "Chile" },
  { code: "CM", name: "Cameroon" }, { code: "CN", name: "China" },
  { code: "CO", name: "Colombia" }, { code: "CR", name: "Costa Rica" },
  { code: "CU", name: "Cuba" }, { code: "CV", name: "Cabo Verde" },
  { code: "CW", name: "Curaçao" }, { code: "CX", name: "Christmas Island" },
  { code: "CY", name: "Cyprus" }, { code: "CZ", name: "Czechia" },
  { code: "DE", name: "Germany" }, { code: "DJ", name: "Djibouti" },
  { code: "DK", name: "Denmark" }, { code: "DM", name: "Dominica" },
  { code: "DO", name: "Dominican Republic" }, { code: "DZ", name: "Algeria" },
  { code: "EC", name: "Ecuador" }, { code: "EE", name: "Estonia" },
  { code: "EG", name: "Egypt" }, { code: "EH", name: "Western Sahara" },
  { code: "ER", name: "Eritrea" }, { code: "ES", name: "Spain" },
  { code: "ET", name: "Ethiopia" }, { code: "FI", name: "Finland" },
  { code: "FJ", name: "Fiji" }, { code: "FK", name: "Falkland Islands" },
  { code: "FM", name: "Micronesia" }, { code: "FO", name: "Faroe Islands" },
  { code: "FR", name: "France" }, { code: "GA", name: "Gabon" },
  { code: "GB", name: "United Kingdom" }, { code: "GD", name: "Grenada" },
  { code: "GE", name: "Georgia" }, { code: "GF", name: "French Guiana" },
  { code: "GG", name: "Guernsey" }, { code: "GH", name: "Ghana" },
  { code: "GI", name: "Gibraltar" }, { code: "GL", name: "Greenland" },
  { code: "GM", name: "Gambia" }, { code: "GN", name: "Guinea" },
  { code: "GP", name: "Guadeloupe" }, { code: "GQ", name: "Equatorial Guinea" },
  { code: "GR", name: "Greece" }, { code: "GS", name: "South Georgia and the South Sandwich Islands" },
  { code: "GT", name: "Guatemala" }, { code: "GU", name: "Guam" },
  { code: "GW", name: "Guinea-Bissau" }, { code: "GY", name: "Guyana" },
  { code: "HK", name: "Hong Kong" }, { code: "HM", name: "Heard Island and McDonald Islands" },
  { code: "HN", name: "Honduras" }, { code: "HR", name: "Croatia" },
  { code: "HT", name: "Haiti" }, { code: "HU", name: "Hungary" },
  { code: "ID", name: "Indonesia" }, { code: "IE", name: "Ireland" },
  { code: "IL", name: "Israel" }, { code: "IM", name: "Isle of Man" },
  { code: "IN", name: "India" }, { code: "IO", name: "British Indian Ocean Territory" },
  { code: "IQ", name: "Iraq" }, { code: "IR", name: "Iran" },
  { code: "IS", name: "Iceland" }, { code: "IT", name: "Italy" },
  { code: "JE", name: "Jersey" }, { code: "JM", name: "Jamaica" },
  { code: "JO", name: "Jordan" }, { code: "JP", name: "Japan" },
  { code: "KE", name: "Kenya" }, { code: "KG", name: "Kyrgyzstan" },
  { code: "KH", name: "Cambodia" }, { code: "KI", name: "Kiribati" },
  { code: "KM", name: "Comoros" }, { code: "KN", name: "Saint Kitts and Nevis" },
  { code: "KP", name: "North Korea" }, { code: "KR", name: "South Korea" },
  { code: "KW", name: "Kuwait" }, { code: "KY", name: "Cayman Islands" },
  { code: "KZ", name: "Kazakhstan" }, { code: "LA", name: "Laos" },
  { code: "LB", name: "Lebanon" }, { code: "LC", name: "Saint Lucia" },
  { code: "LI", name: "Liechtenstein" }, { code: "LK", name: "Sri Lanka" },
  { code: "LR", name: "Liberia" }, { code: "LS", name: "Lesotho" },
  { code: "LT", name: "Lithuania" }, { code: "LU", name: "Luxembourg" },
  { code: "LV", name: "Latvia" }, { code: "LY", name: "Libya" },
  { code: "MA", name: "Morocco" }, { code: "MC", name: "Monaco" },
  { code: "MD", name: "Moldova" }, { code: "ME", name: "Montenegro" },
  { code: "MF", name: "Saint Martin (French part)" }, { code: "MG", name: "Madagascar" },
  { code: "MH", name: "Marshall Islands" }, { code: "MK", name: "North Macedonia" },
  { code: "ML", name: "Mali" }, { code: "MM", name: "Myanmar" },
  { code: "MN", name: "Mongolia" }, { code: "MO", name: "Macao" },
  { code: "MP", name: "Northern Mariana Islands" }, { code: "MQ", name: "Martinique" },
  { code: "MR", name: "Mauritania" }, { code: "MS", name: "Montserrat" },
  { code: "MT", name: "Malta" }, { code: "MU", name: "Mauritius" },
  { code: "MV", name: "Maldives" }, { code: "MW", name: "Malawi" },
  { code: "MX", name: "Mexico" }, { code: "MY", name: "Malaysia" },
  { code: "MZ", name: "Mozambique" }, { code: "NA", name: "Namibia" },
  { code: "NC", name: "New Caledonia" }, { code: "NE", name: "Niger" },
  { code: "NF", name: "Norfolk Island" }, { code: "NG", name: "Nigeria" },
  { code: "NI", name: "Nicaragua" }, { code: "NL", name: "Netherlands" },
  { code: "NO", name: "Norway" }, { code: "NP", name: "Nepal" },
  { code: "NR", name: "Nauru" }, { code: "NU", name: "Niue" },
  { code: "NZ", name: "New Zealand" }, { code: "OM", name: "Oman" },
  { code: "PA", name: "Panama" }, { code: "PE", name: "Peru" },
  { code: "PF", name: "French Polynesia" }, { code: "PG", name: "Papua New Guinea" },
  { code: "PH", name: "Philippines" }, { code: "PK", name: "Pakistan" },
  { code: "PL", name: "Poland" }, { code: "PM", name: "Saint Pierre and Miquelon" },
  { code: "PN", name: "Pitcairn" }, { code: "PR", name: "Puerto Rico" },
  { code: "PS", name: "Palestine" }, { code: "PT", name: "Portugal" },
  { code: "PW", name: "Palau" }, { code: "PY", name: "Paraguay" },
  { code: "QA", name: "Qatar" }, { code: "RE", name: "Réunion" },
  { code: "RO", name: "Romania" }, { code: "RS", name: "Serbia" },
  { code: "RU", name: "Russia" }, { code: "RW", name: "Rwanda" },
  { code: "SA", name: "Saudi Arabia" }, { code: "SB", name: "Solomon Islands" },
  { code: "SC", name: "Seychelles" }, { code: "SD", name: "Sudan" },
  { code: "SE", name: "Sweden" }, { code: "SG", name: "Singapore" },
  { code: "SH", name: "Saint Helena, Ascension and Tristan da Cunha" }, { code: "SI", name: "Slovenia" },
  { code: "SJ", name: "Svalbard and Jan Mayen" }, { code: "SK", name: "Slovakia" },
  { code: "SL", name: "Sierra Leone" }, { code: "SM", name: "San Marino" },
  { code: "SN", name: "Senegal" }, { code: "SO", name: "Somalia" },
  { code: "SR", name: "Suriname" }, { code: "SS", name: "South Sudan" },
  { code: "ST", name: "Sao Tome and Principe" }, { code: "SV", name: "El Salvador" },
  { code: "SX", name: "Sint Maarten (Dutch part)" }, { code: "SY", name: "Syria" },
  { code: "SZ", name: "Eswatini" }, { code: "TC", name: "Turks and Caicos Islands" },
  { code: "TD", name: "Chad" }, { code: "TF", name: "French Southern Territories" },
  { code: "TG", name: "Togo" }, { code: "TH", name: "Thailand" },
  { code: "TJ", name: "Tajikistan" }, { code: "TK", name: "Tokelau" },
  { code: "TL", name: "Timor-Leste" }, { code: "TM", name: "Turkmenistan" },
  { code: "TN", name: "Tunisia" }, { code: "TO", name: "Tonga" },
  { code: "TR", name: "Turkey" }, { code: "TT", name: "Trinidad and Tobago" },
  { code: "TV", name: "Tuvalu" }, { code: "TW", name: "Taiwan" },
  { code: "TZ", name: "Tanzania" }, { code: "UA", name: "Ukraine" },
  { code: "UG", name: "Uganda" }, { code: "UM", name: "United States Minor Outlying Islands" },
  { code: "US", name: "United States" }, { code: "UY", name: "Uruguay" },
  { code: "UZ", name: "Uzbekistan" }, { code: "VA", name: "Holy See" },
  { code: "VC", name: "Saint Vincent and the Grenadines" }, { code: "VE", name: "Venezuela" },
  { code: "VG", name: "Virgin Islands (British)" }, { code: "VI", name: "Virgin Islands (U.S.)" },
  { code: "VN", name: "Vietnam" }, { code: "VU", name: "Vanuatu" },
  { code: "WF", name: "Wallis and Futuna" }, { code: "WS", name: "Samoa" },
  { code: "YE", name: "Yemen" }, { code: "YT", name: "Mayotte" },
  { code: "ZA", name: "South Africa" }, { code: "ZM", name: "Zambia" },
  { code: "ZW", name: "Zimbabwe" },
]

// Complete IANA timezone database used as a fallback when
// Intl.supportedValuesOf("timeZone") is unavailable. This mirrors the canonical
// tz database so the dropdown is never missing a zone.
export const FALLBACK_TIMEZONES: string[] = [
  "Africa/Abidjan", "Africa/Accra", "Africa/Addis_Ababa", "Africa/Algiers",
  "Africa/Cairo", "Africa/Casablanca", "Africa/Ceuta", "Africa/Johannesburg",
  "Africa/Juba", "Africa/Kampala", "Africa/Lagos", "Africa/Maputo",
  "Africa/Monrovia", "Africa/Nairobi", "Africa/Ndjamena", "Africa/Tunis",
  "Africa/Windhoek", "America/Adak", "America/Anchorage", "America/Araguaina",
  "America/Argentina/Buenos_Aires", "America/Argentina/Catamarca",
  "America/Argentina/Cordoba", "America/Argentina/Jujuy", "America/Argentina/La_Rioja",
  "America/Argentina/Mendoza", "America/Argentina/Rio_Gallegos", "America/Argentina/Salta",
  "America/Argentina/San_Juan", "America/Argentina/San_Luis", "America/Argentina/Tucuman",
  "America/Argentina/Ushuaia", "America/Asuncion", "America/Atikokan", "America/Bahia",
  "America/Bahia_Banderas", "America/Barbados", "America/Belem", "America/Belize",
  "America/Blanc-Sablon", "America/Boa_Vista", "America/Bogota", "America/Boise",
  "America/Cambridge_Bay", "America/Campo_Grande", "America/Cancun", "America/Caracas",
  "America/Cayenne", "America/Chicago", "America/Chihuahua", "America/Ciudad_Juarez",
  "America/Costa_Rica", "America/Creston", "America/Cuiaba", "America/Curacao",
  "America/Danmarkshavn", "America/Dawson", "America/Dawson_Creek", "America/Denver",
  "America/Detroit", "America/Edmonton", "America/Eirunepe", "America/El_Salvador",
  "America/Fort_Nelson", "America/Fortaleza", "America/Glace_Bay", "America/Goose_Bay",
  "America/Grand_Turk", "America/Guatemala", "America/Guayaquil", "America/Guyana",
  "America/Halifax", "America/Havana", "America/Hermosillo", "America/Indiana/Indianapolis",
  "America/Indiana/Knox", "America/Indiana/Marengo", "America/Indiana/Petersburg",
  "America/Indiana/Tell_City", "America/Indiana/Vevay", "America/Indiana/Vincennes",
  "America/Indiana/Winamac", "America/Inuvik", "America/Iqaluit", "America/Jamaica",
  "America/Juneau", "America/Kentucky/Louisville", "America/Kentucky/Monticello",
  "America/La_Paz", "America/Lima", "America/Los_Angeles", "America/Maceio",
  "America/Managua", "America/Manaus", "America/Martinique", "America/Matamoros",
  "America/Mazatlan", "America/Menominee", "America/Merida", "America/Metlakatla",
  "America/Mexico_City", "America/Miquelon", "America/Moncton", "America/Monterrey",
  "America/Montevideo", "America/New_York", "America/Nome", "America/Noronha",
  "America/North_Dakota/Beulah", "America/North_Dakota/Center", "America/North_Dakota/New_Salem",
  "America/Nuuk", "America/Ojinaga", "America/Panama", "America/Paramaribo",
  "America/Phoenix", "America/Port-au-Prince", "America/Porto_Velho", "America/Puerto_Rico",
  "America/Punta_Arenas", "America/Rankin_Inlet", "America/Recife", "America/Regina",
  "America/Resolute", "America/Rio_Branco", "America/Santarem", "America/Santiago",
  "America/Santo_Domingo", "America/Sao_Paulo", "America/Scoresbysund", "America/Sitka",
  "America/St_Johns", "America/Swift_Current", "America/Tegucigalpa", "America/Thule",
  "America/Tijuana", "America/Toronto", "America/Vancouver", "America/Whitehorse",
  "America/Winnipeg", "America/Yakutat", "America/Yellowknife", "Antarctica/Casey",
  "Antarctica/Davis", "Antarctica/DumontDUrville", "Antarctica/Macquarie",
  "Antarctica/Mawson", "Antarctica/McMurdo", "Antarctica/Palmer", "Antarctica/Rothera",
  "Antarctica/Syowa", "Antarctica/Troll", "Antarctica/Vostok", "Asia/Almaty",
  "Asia/Amman", "Asia/Anadyr", "Asia/Aqtau", "Asia/Aqtobe", "Asia/Ashgabat",
  "Asia/Atyrau", "Asia/Baghdad", "Asia/Baku", "Asia/Bangkok", "Asia/Barnaul",
  "Asia/Beirut", "Asia/Bishkek", "Asia/Brunei", "Asia/Chita", "Asia/Choibalsan",
  "Asia/Colombo", "Asia/Damascus", "Asia/Dhaka", "Asia/Dili", "Asia/Dubai",
  "Asia/Dushanbe", "Asia/Famagusta", "Asia/Gaza", "Asia/Hebron", "Asia/Ho_Chi_Minh",
  "Asia/Hong_Kong", "Asia/Hovd", "Asia/Irkutsk", "Asia/Jakarta", "Asia/Jayapura",
  "Asia/Jerusalem", "Asia/Kabul", "Asia/Kamchatka", "Asia/Karachi", "Asia/Kathmandu",
  "Asia/Khandyga", "Asia/Kolkata", "Asia/Kuala_Lumpur", "Asia/Kuching", "Asia/Macau",
  "Asia/Magadan", "Asia/Makassar", "Asia/Manila", "Asia/Nicosia", "Asia/Novokuznetsk",
  "Asia/Novosibirsk", "Asia/Omsk", "Asia/Oral", "Asia/Pontianak", "Asia/Pyongyang",
  "Asia/Qatar", "Asia/Qostanay", "Asia/Qyzylorda", "Asia/Riyadh", "Asia/Sakhalin",
  "Asia/Samarkand", "Asia/Seoul", "Asia/Shanghai", "Asia/Singapore", "Asia/Srednekolymsk",
  "Asia/Taipei", "Asia/Tashkent", "Asia/Tbilisi", "Asia/Tehran", "Asia/Thimphu",
  "Asia/Tokyo", "Asia/Tomsk", "Asia/Ulaanbaatar", "Asia/Urumqi", "Asia/Ust-Nera",
  "Asia/Vientiane", "Asia/Vladivostok", "Asia/Yakutsk", "Asia/Yangon", "Asia/Yekaterinburg",
  "Asia/Yerevan", "Atlantic/Azores", "Atlantic/Bermuda", "Atlantic/Canary",
  "Atlantic/Cape_Verde", "Atlantic/Faroe", "Atlantic/Madeira", "Atlantic/Reykjavik",
  "Atlantic/South_Georgia", "Atlantic/Stanley", "Australia/Adelaide", "Australia/Brisbane",
  "Australia/Broken_Hill", "Australia/Darwin", "Australia/Eucla", "Australia/Hobart",
  "Australia/Lindeman", "Australia/Lord_Howe", "Australia/Perth", "Australia/Sydney",
  "Europe/Amsterdam", "Europe/Andorra", "Europe/Astrakhan", "Europe/Athens",
  "Europe/Belgrade", "Europe/Berlin", "Europe/Bratislava", "Europe/Brussels",
  "Europe/Bucharest", "Europe/Budapest", "Europe/Chisinau", "Europe/Copenhagen",
  "Europe/Dublin", "Europe/Gibraltar", "Europe/Guernsey", "Europe/Helsinki",
  "Europe/Isle_of_Man", "Europe/Istanbul", "Europe/Jersey", "Europe/Kaliningrad",
  "Europe/Kiev", "Europe/Kirov", "Europe/Lisbon", "Europe/Ljubljana", "Europe/London",
  "Europe/Luxembourg", "Europe/Madrid", "Europe/Malta", "Europe/Mariehamn",
  "Europe/Minsk", "Europe/Monaco", "Europe/Moscow", "Europe/Oslo", "Europe/Paris",
  "Europe/Podgorica", "Europe/Prague", "Europe/Riga", "Europe/Rome", "Europe/Samara",
  "Europe/San_Marino", "Europe/Sarajevo", "Europe/Saratov", "Europe/Simferopol",
  "Europe/Skopje", "Europe/Sofia", "Europe/Stockholm", "Europe/Tallinn",
  "Europe/Tirane", "Europe/Ulyanovsk", "Europe/Vaduz", "Europe/Vatican",
  "Europe/Vienna", "Europe/Vilnius", "Europe/Volgograd", "Europe/Warsaw",
  "Europe/Zagreb", "Europe/Zurich", "Indian/Antananarivo", "Indian/Chagos",
  "Indian/Christmas", "Indian/Cocos", "Indian/Comoro", "Indian/Kerguelen",
  "Indian/Mahe", "Indian/Maldives", "Indian/Mauritius", "Indian/Mayotte",
  "Indian/Reunion", "Pacific/Apia", "Pacific/Auckland", "Pacific/Bougainville",
  "Pacific/Chatham", "Pacific/Chuuk", "Pacific/Easter", "Pacific/Efate",
  "Pacific/Fakaofo", "Pacific/Fiji", "Pacific/Funafuti", "Pacific/Galapagos",
  "Pacific/Gambier", "Pacific/Guadalcanal", "Pacific/Guam", "Pacific/Honolulu",
  "Pacific/Kanton", "Pacific/Kiritimati", "Pacific/Kosrae", "Pacific/Kwajalein",
  "Pacific/Majuro", "Pacific/Marquesas", "Pacific/Midway", "Pacific/Nauru",
  "Pacific/Niue", "Pacific/Norfolk", "Pacific/Noumea", "Pacific/Pago_Pago",
  "Pacific/Palau", "Pacific/Pitcairn", "Pacific/Pohnpei", "Pacific/Port_Moresby",
  "Pacific/Rarotonga", "Pacific/Saipan", "Pacific/Tahiti", "Pacific/Tarawa",
  "Pacific/Tongatapu", "Pacific/Wake", "Pacific/Wallis", "UTC",
]
